# @package _global_

train:
  save_root: './ckpts/exp'
  base_dir: '/com_base'
  save_dir: '/com_bridge'
  log_file: 'log.txt'
  batch_size: 64
  is_continue: false
  distributed: true

  base:
    scale: 1.0
    
  bridge:
    num_epoch: 10000
    warmup_epoch: 100
    num_eval: 200

    lr: 5e-4
    lr_min: 1e-4
    weight_decay: 1e-4
    clip_norm: false

    sig_min: 1.0
    sig_max: 3.0
    noise_type: exp
    init_type: const
    num_step: 1000
    noise_decay: true

    use_global_embed: true
    load_best_base: false

  sampler:
    num_sample: 20

model:
  base:
    add_noise: false
    dec:
      n_layers: 4
    quantizer:
      q_level: [5,5,5,5,5,5]
      num_layers: 5
      max_node_num: 20
  bridge:
    n_head: 8
    n_layers: 4