# @package _global_

train:
  save_root: './ckpts/exp'
  save_dir: '/com_base'
  log_file: 'log.txt'
  batch_size: 32
  is_continue: false
  distributed: true
  
  base:
    num_epoch: 3000
    num_eval: 60

    lr: 5e-4
    weight_decay: 1e-4
    clip_norm: false
    scale: 1.0

model:
  base:
    add_noise: false
    dec:
      n_layers: 4
    quantizer:
      q_level: [5,5,5,5,5,5]
      num_layers: 5
      max_node_num: 20