# @package _global_

train:
  save_root: './ckpts/exp'
  base_dir: '/zinc_base'
  save_dir: '/zinc_bridge'
  log_file: 'log.txt'
  batch_size: 512
  is_continue: false
  distributed: true

  base:
    scale: 3.0
    
  bridge:
    num_epoch: 2000
    warmup_epoch: 10
    num_eval: 40

    lr: 2e-3
    lr_min: 1e-4
    weight_decay: 1e-4
    clip_norm: false

    sig_min: 1.0
    sig_max: 3.0
    noise_type: exp
    init_type: const
    num_step: 1000
    noise_decay: true

    use_global_embed: true
    load_best_base: true

  sampler:
    num_sample: 1000

model:
  base:
    dec:
      n_layers: 4
    quantizer:
      q_level: [5,5,5,5,5,5]
      num_layers: 5
      max_node_num: 38
  bridge:
    n_layers: 8